#! usr/bin/perl

 $range=15;
 $ctrl=0;
 $filename= 'alutest.txt';

 open(INFO, '>', 'alutest.txt');

 for ($i=0;$i<32;$i++)
 {
        $A= int(rand($range));
        $B= int(rand($range));
        $Z= int(rand($range));
        $Z_tmp1 = 0;
        $Z_tmp2 = "";
        $ctrl=$Z%4;

        if ($ctrl==0)
        {
            $Z=$A+$B;
            if($Z>15)
            {
                $Z=$Z %16;
            }
        }
        elsif($ctrl==1)
        {
            $Z = $A & $B;
        }
        elsif($ctrl == 2)
        {
           $Z_tmp1 = $A << $B;
           $Z_tmp2 = sprintf('%04b', $Z_tmp1);
           $Z = substr($Z_tmp2, length($Z_tmp2)-4,4);
        }
        else
        {
            $Z = $A >> $B;
        }
        if($ctrl == 2)
        {
            printf INFO "%04b%04b%02b", $A, $B, $ctrl;
            printf INFO $Z."\n";
        }
        else
        {
            printf INFO "%04b%04b%02b%04b\n", $A, $B, $ctrl, $Z;
        }
 }

